import React from 'react';

function App() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto p-8">
        <h1 className="text-4xl font-bold mb-4">Welcome to Anima Project</h1>
        <p className="text-lg text-muted-foreground">
          This project has been automatically generated by Anima.
        </p>
      </div>
    </div>
  );
}

export default App;